name: Makefile CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    update_zip:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Exit if last commit was by github-actions
          id: check_author
          run: |
            AUTHOR=$(git log -1 --pretty=format:'%an')
            echo "Last commit author: $AUTHOR"
            echo "author=$AUTHOR" >> "$GITHUB_OUTPUT"

        - name: Set up SSH
          if: steps.check_author.outputs.author != 'github_actions'
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts

        - name: Set up Git
          if: steps.check_author.outputs.author != 'github_actions'
          run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git remote set-url origin git@github.com:0david0mp/pallestra_webapp.git

        - name: Create zip archive
          if: steps.check_author.outputs.author != 'github_actions'
          run: |
              make progweb_2025_david_mieres.zip

        - name: Commit ZIP archive
          if: steps.check_author.outputs.author != 'github_actions'
          run: |
            git fetch
            git add progweb_2025_david_mieres.zip
            git commit -m "zip automated update" || echo "No changes to commit"
            git push
