name: Makefile CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    update_zip:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Create zip archive
          run: make progweb_2025_david_mieres.zip
